### ISSUE TITLE
Config loading with provision for local overrides

### ISSUE THREAD

**Issue by deb-sandeep** [deb-sandeep/JoveNotesProcessor#2]
### Change driver

JoveNotes Processor (JNP) should be customizable per installation and development environment, through local command line options and configuration values. This will enable a smoother multi developer collaboration, deployment into diverse environments, running multiple instances on the same machine. All this can be done without exposing the local configuration via the source control.
### Current situation

JNP currently looks for a config.properties resource in classpath and loads it. JNP can further override the configuration file values with command line options.
### Proposed change

We use the standard configuration override pattern to enable local (non version controlled) configurations. The proposed changes are as follows:
1. JNP first attempts to load /config.properties resource from the classpath. If found, it loads it in memory. If not found, it goes forward.
2. Next, JNP attempts to load a user specific configuration from `~/.jnp/config.properties`. If found, these properties will be loaded overriding the corresponding values in the /config.properties classpath resource.
3. Lastly, JNP should look for an optional `--configPath` command line option, the value of which is the **absolute** path of the configuration property file. If found, this will supersede the corresponding configuration values.
4. At the end, if a corresponding configuration value is provided via command line (for example `--dbPassword` or `--wordnicKey`), these take ultimate precedence.
### Notes

This change will be first implemented in the notes_preview branch.

**Comment by vivekkant** [comment]
I have checked in the changes with the commit 2e01ffc. Please review.

**Comment by deb-sandeep** [comment]
Reviewed and hardened.
